import type { GameConfig } from "@/types/game-config";

export function generateGameConfigPy(c: GameConfig): string {
  const paytableLines = c.symbols
    .filter((s) => Object.keys(s.paytable).length > 0)
    .flatMap((s) =>
      Object.entries(s.paytable)
        .filter(([, v]) => v > 0)
        .map(([k, v]) => `        (${k}, "${s.name}"): ${v},`)
    )
    .join("\n");

  const specials = c.symbols.filter((s) => s.type === "wild" || s.type === "scatter" || s.type === "bonus").map((s) => `"${s.name}"`);

  const modes = [`        {"name": "${c.baseBetMode.name}", "cost": ${c.baseBetMode.cost}}`];
  if (c.freeSpins.enabled) {
    modes.push(`        {"name": "${c.freeSpins.modeName}", "cost": ${c.freeSpins.costMultiplier}}`);
  }

  return `from math_sdk.config import Config


class GameConfig(Config):
    """
    ${c.gameName || "Untitled Game"} — Auto-generated by Stake Engine Slot Builder
    Game ID: ${c.gameId || "untitled"}
    Version: ${c.gameVersion}
    """

    def __init__(self):
        super().__init__()

        # Grid
        self.num_reels = ${c.numReels}
        self.num_rows = ${c.numRows}

        # Win Mechanic
        self.win_mechanic = "${c.winMechanic}"
${c.winMechanic === "lines" ? `        self.num_paylines = ${c.numPaylines}` : ""}
        self.tumble_enabled = ${c.tumbleEnabled ? "True" : "False"}

        # Paytable: { (match_count, symbol_name): multiplier }
        self.paytable = {
${paytableLines}
        }

        # Special symbols
        self.special_symbols = [${specials.join(", ")}]

        # Reels
        self.reels = {
            "BR0": "BR0.csv",
${c.freeSpins.enabled ? '            "FR0": "FR0.csv",' : ""}
        }

        # Bet Modes
        self.bet_modes = [
${modes.join(",\n")}
        ]

        # RTP & Simulation
        self.rtp_target = ${c.rtpTarget}
        self.volatility = "${c.volatility}"
        self.simulations = ${c.simulations}
${c.freeSpins.enabled ? `
        # Free Spins
        self.free_spins = {
            "scatter_awards": ${JSON.stringify(c.freeSpins.scatterAwards)},
            "multiplier": "${c.freeSpins.multiplier}",
            "retrigger": ${c.freeSpins.retrigger ? "True" : "False"},
        }` : ""}
`;
}

export function generateIndexJson(c: GameConfig): string {
  const modes: object[] = [
    {
      name: c.baseBetMode.name,
      cost: c.baseBetMode.cost,
      events: `books_${c.baseBetMode.name}.jsonl.zst`,
      weights: `lookUpTable_${c.baseBetMode.name}_0.csv`,
    },
  ];
  if (c.freeSpins.enabled) {
    modes.push({
      name: c.freeSpins.modeName,
      cost: c.freeSpins.costMultiplier,
      events: `books_${c.freeSpins.modeName}.jsonl.zst`,
      weights: `lookUpTable_${c.freeSpins.modeName}_0.csv`,
    });
  }
  return JSON.stringify({ modes }, null, 2);
}

export function generateSampleBooks(c: GameConfig): string {
  const board = Array.from({ length: c.numReels }, () =>
    Array.from({ length: c.numRows }, () => c.symbols[Math.floor(Math.random() * c.symbols.length)].name)
  );
  return JSON.stringify(
    {
      id: 1,
      events: [
        { index: 0, type: "reveal", board, gameType: "basegame" },
        { index: 1, type: "winInfo", totalWin: 10, wins: [] },
        { index: 2, type: "setWin", amount: 10 },
        { index: 3, type: "finalWin", amount: 10 },
      ],
      payoutMultiplier: 10,
    },
    null,
    2
  );
}

export function generateSampleCSV(): string {
  return `simulationID,weight,payoutMultiplier
1,199895486317,0
2,25668581149,20
3,15000000000,50
4,5000000000,100
5,1000000000,500`;
}

export function generateDesignJson(c: GameConfig): string {
  return JSON.stringify(c, null, 2);
}

export function generateChecklist(c: GameConfig): string {
  return `# ${c.gameName || "Untitled Game"} — Submission Checklist

## Game: ${c.gameId || "untitled"} v${c.gameVersion}

### Math SDK
- [ ] game_config.py placed in games/${c.gameId}/
- [ ] Base reel strips created (BR0.csv)
${c.freeSpins.enabled ? "- [ ] Free spin reel strips created (FR0.csv)" : ""}
- [ ] Simulations run (${c.simulations.toLocaleString()}+ per mode)
- [ ] RTP verified at ${c.rtpTarget}%
- [ ] Optimization run (run_optimization: True)
- [ ] Output files in library/publish_files/

### Output Files
- [ ] index.json — mode manifest
- [ ] books_${c.baseBetMode.name}.jsonl.zst — base game rounds
${c.freeSpins.enabled ? `- [ ] books_${c.freeSpins.modeName}.jsonl.zst — bonus rounds` : ""}
- [ ] lookUpTable_${c.baseBetMode.name}_0.csv — base weights
${c.freeSpins.enabled ? `- [ ] lookUpTable_${c.freeSpins.modeName}_0.csv — bonus weights` : ""}
- [ ] payoutMultiplier matches between CSV and .jsonl.zst (les valeurs doivent correspondre exactement — vérification/hash côté Stake à l’upload)

### Compliance
- [ ] Game is fully stateless
- [ ] No jackpots, gamble, early cashout, or progression features
- [ ] All outcomes are pre-simulated
- [ ] RTP calculable from CSV weights

### Frontend SDK
- [ ] Web SDK cloned from https://github.com/StakeEngine/web-sdk
- [ ] Game events rendered in Storybook
- [ ] All event types handled (reveal, winInfo, setWin, finalWin)

### RGS Integration
- [ ] TS Client connected: https://github.com/StakeEngine/ts-client
- [ ] /wallet/authenticate working
- [ ] /wallet/play tested
- [ ] /wallet/end-round tested
- [ ] CDN URL: https://{TeamName}.cdn.stake-engine.com/${c.gameId}/${c.gameVersion}/index.html
`;
}
