export const DOCS = {
  hub: "https://stakeengine.github.io/math-sdk/",
  math: {
    home: "https://stakeengine.github.io/math-sdk/math_home/",
    engineSetup: "https://stakeengine.github.io/math-sdk/math_docs/general_overview/",
    quickstart: "https://stakeengine.github.io/math-sdk/math_docs/quickstart/",
    gameStructure: "https://stakeengine.github.io/math-sdk/math_docs/overview_section/game_struct/",
    gameFormat: "https://stakeengine.github.io/math-sdk/math_docs/overview_section/game_format/",
    stateMachine: "https://stakeengine.github.io/math-sdk/math_docs/overview_section/state_overview/",
    symbols: "https://stakeengine.github.io/math-sdk/math_docs/gamestate_section/syms_board_section/symbol_info/",
    board: "https://stakeengine.github.io/math-sdk/math_docs/gamestate_section/syms_board_section/board_info/",
    wins: "https://stakeengine.github.io/math-sdk/math_docs/gamestate_section/win_info/",
    events: "https://stakeengine.github.io/math-sdk/math_docs/gamestate_section/events_info/",
    config: "https://stakeengine.github.io/math-sdk/math_docs/gamestate_section/configuration_section/config_overview/",
    betMode: "https://stakeengine.github.io/math-sdk/math_docs/gamestate_section/configuration_section/betmode_overview/",
    distribution: "https://stakeengine.github.io/math-sdk/math_docs/gamestate_section/configuration_section/betmode_dist/",
    lines: "https://stakeengine.github.io/math-sdk/math_docs/source_section/lines_info/",
    ways: "https://stakeengine.github.io/math-sdk/math_docs/source_section/ways_info/",
    cluster: "https://stakeengine.github.io/math-sdk/math_docs/source_section/cluster_info/",
    scatter: "https://stakeengine.github.io/math-sdk/math_docs/source_section/scatter_info/",
    tumble: "https://stakeengine.github.io/math-sdk/math_docs/source_section/tumble_info/",
    winManager: "https://stakeengine.github.io/math-sdk/math_docs/source_section/win_manager/",
    executables: "https://stakeengine.github.io/math-sdk/math_docs/source_section/executables_info/",
    optimization: "https://stakeengine.github.io/math-sdk/math_docs/optimization_section/optimization_algorithm/",
    examples: "https://stakeengine.github.io/math-sdk/math_docs/sample_section/sample_games/",
    force: "https://stakeengine.github.io/math-sdk/math_docs/gamestate_section/force_info/",
    uploads: "https://stakeengine.github.io/math-sdk/math_docs/uploads_section/upload_info/",
    directory: "https://stakeengine.github.io/math-sdk/math_docs/directory/",
  },
  fe: {
    home: "https://stakeengine.github.io/math-sdk/fe_home/",
    dependencies: "https://stakeengine.github.io/math-sdk/fe_docs/dependencies/",
    getStarted: "https://stakeengine.github.io/math-sdk/fe_docs/get_started/",
    storybook: "https://stakeengine.github.io/math-sdk/fe_docs/explore_sb/",
    flowchart: "https://stakeengine.github.io/math-sdk/fe_docs/flowchart/",
    fileStruct: "https://stakeengine.github.io/math-sdk/fe_docs/file_struct/",
    ui: "https://stakeengine.github.io/math-sdk/fe_docs/ui/",
    events: "https://stakeengine.github.io/math-sdk/fe_docs/steps/",
    context: "https://stakeengine.github.io/math-sdk/fe_docs/context/",
    taskBreakdown: "https://stakeengine.github.io/math-sdk/fe_docs/task_bd/",
  },
  rgs: {
    api: "https://stakeengine.github.io/math-sdk/rgs_docs/RGS/",
    dataFormat: "https://stakeengine.github.io/math-sdk/rgs_docs/data_format/",
    example: "https://stakeengine.github.io/math-sdk/simple_example/simple_example/",
  },
  github: {
    mathSdk: "https://github.com/StakeEngine/math-sdk",
    webSdk: "https://github.com/StakeEngine/web-sdk",
    tsClient: "https://github.com/StakeEngine/ts-client",
  },
} as const;

export const WIN_MECHANIC_DOCS: Record<string, string> = {
  lines: DOCS.math.lines,
  ways: DOCS.math.ways,
  cluster: DOCS.math.cluster,
  scatter: DOCS.math.scatter,
};
