import { useMemo } from "react";
import { useMathConfig } from "@/context/MathConfigContext";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { Copy, Download, Bug, AlertTriangle, ExternalLink } from "lucide-react";
import { toast } from "sonner";

export function MathRunPy() {
  const { mathConfig, updateRunConfig, setDebugMode } = useMathConfig();
  const { runConfig } = mathConfig;

  const generatedCode = useMemo(() => {
    return `"""
Stake Engine Math SDK - Run Configuration
Generated by Stake Engine Builder
Documentation: https://stakeengine.github.io/math-sdk/math_docs/quickstart/
"""

from game_config import GameConfig
from gamestate import GameState

# Threading Configuration
num_threads = ${runConfig.numThreads}  # CPU threads for Python simulation
rust_threads = ${runConfig.rustThreads}  # Rust optimization threads (requires Cargo)
batching_size = ${runConfig.batchingSize}

# Output Configuration
compression = ${runConfig.compression ? "True" : "False"}  # True = .json.zst (production), False = .json (debug)

# Simulation Arguments per BetMode
num_sim_args = {
    "base": ${runConfig.numSimBase},  # Min recommended for production: 100,000
    "bonus": ${runConfig.numSimBonus},
}

# Run Conditions
run_sims = ${runConfig.runSims ? "True" : "False"}  # Generate simulation data
run_optimization = ${runConfig.runOptimization ? "True" : "False"}  # Optimize weights via Rust (requires Cargo)
run_analysis = ${runConfig.runAnalysis ? "True" : "False"}  # Generate PAR sheet (.xlsx)
upload_data = ${runConfig.uploadData ? "True" : "False"}  # Upload to AWS S3

if __name__ == "__main__":
    config = GameConfig()
    
    if run_sims:
        from stake_engine import run_simulations
        run_simulations(
            config=config,
            gamestate_class=GameState,
            num_threads=num_threads,
            batching_size=batching_size,
            num_sim_args=num_sim_args,
            compression=compression,
        )
    
    if run_optimization:
        from stake_engine import run_rust_optimization
        run_rust_optimization(
            config=config,
            num_threads=rust_threads,
        )
    
    if run_analysis:
        from stake_engine import generate_par_sheet
        generate_par_sheet(config=config)
    
    if upload_data:
        from stake_engine import upload_to_s3
        upload_to_s3(config=config)
`;
  }, [runConfig]);

  const handleCopy = () => {
    navigator.clipboard.writeText(generatedCode);
    toast.success("Code copié !");
  };

  const handleDownload = () => {
    const blob = new Blob([generatedCode], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "run.py";
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6">
      {/* Quick Actions */}
      <div className="flex gap-2">
        <Button variant="outline" onClick={setDebugMode} className="border-primary/50 text-primary hover:bg-primary/10">
          <Bug className="h-4 w-4 mr-2" /> Mode Debug (100 sims)
        </Button>
        <a
          href="https://stakeengine.github.io/math-sdk/math_docs/quickstart/"
          target="_blank"
          rel="noopener noreferrer"
          className="inline-flex items-center gap-2 text-sm text-primary hover:underline"
        >
          📚 Documentation run.py <ExternalLink className="h-3 w-3" />
        </a>
      </div>

      {/* Config Form */}
      <div className="grid gap-6 md:grid-cols-2">
        {/* Threading */}
        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-sm">Threading</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div>
              <Label htmlFor="numThreads" className="flex items-center gap-2">
                num_threads
                <span className="text-xs text-muted-foreground">(CPU parallèles)</span>
              </Label>
              <Input
                id="numThreads"
                type="number"
                min={1}
                max={64}
                value={runConfig.numThreads}
                onChange={(e) => updateRunConfig({ numThreads: parseInt(e.target.value) || 10 })}
              />
            </div>
            <div>
              <Label htmlFor="rustThreads" className="flex items-center gap-2">
                rust_threads
                <span className="text-xs text-muted-foreground">(optimisation Rust)</span>
              </Label>
              <Input
                id="rustThreads"
                type="number"
                min={1}
                max={64}
                value={runConfig.rustThreads}
                onChange={(e) => updateRunConfig({ rustThreads: parseInt(e.target.value) || 10 })}
              />
            </div>
            <div>
              <Label htmlFor="batchingSize">batching_size</Label>
              <Input
                id="batchingSize"
                type="number"
                min={100}
                max={10000}
                value={runConfig.batchingSize}
                onChange={(e) => updateRunConfig({ batchingSize: parseInt(e.target.value) || 1000 })}
              />
            </div>
          </CardContent>
        </Card>

        {/* Simulations */}
        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-sm">Simulations</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div>
              <Label htmlFor="numSimBase" className="flex items-center gap-2">
                num_sim base
                <span className="text-xs text-primary">⚠️ min production: 100k</span>
              </Label>
              <Input
                id="numSimBase"
                type="number"
                min={100}
                max={10000000}
                value={runConfig.numSimBase}
                onChange={(e) => updateRunConfig({ numSimBase: parseInt(e.target.value) || 100000 })}
              />
            </div>
            <div>
              <Label htmlFor="numSimBonus">num_sim bonus</Label>
              <Input
                id="numSimBonus"
                type="number"
                min={100}
                max={10000000}
                value={runConfig.numSimBonus}
                onChange={(e) => updateRunConfig({ numSimBonus: parseInt(e.target.value) || 100000 })}
              />
            </div>
            <div className="flex items-center gap-2">
              <Switch
                id="compression"
                checked={runConfig.compression}
                onCheckedChange={(checked) => updateRunConfig({ compression: checked })}
              />
              <Label htmlFor="compression" className="text-sm">
                compression (.json.zst)
              </Label>
            </div>
          </CardContent>
        </Card>

        {/* Run Conditions */}
        <Card className="md:col-span-2">
          <CardHeader className="pb-3">
            <CardTitle className="text-sm">Conditions d'exécution</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
              <div className="flex items-center gap-2">
                <Switch
                  id="runSims"
                  checked={runConfig.runSims}
                  onCheckedChange={(checked) => updateRunConfig({ runSims: checked })}
                />
                <Label htmlFor="runSims" className="text-sm">run_sims</Label>
              </div>
              <div className="flex items-center gap-2">
                <Switch
                  id="runOptimization"
                  checked={runConfig.runOptimization}
                  onCheckedChange={(checked) => updateRunConfig({ runOptimization: checked })}
                />
                <Label htmlFor="runOptimization" className="text-sm flex items-center gap-1">
                  run_optimization
                  <span className="text-xs text-primary">⚠️ Rust</span>
                </Label>
              </div>
...
            </div>
            {runConfig.runOptimization && (
              <div className="mt-4 p-3 rounded-lg border border-primary/30 bg-primary/10 flex items-start gap-2">
                <AlertTriangle className="h-4 w-4 text-primary shrink-0 mt-0.5" />
                <p className="text-xs text-primary">
                  L'optimisation Rust nécessite Cargo installé. Voir{" "}
                  <a href="https://rustup.rs" target="_blank" rel="noopener noreferrer" className="underline">
                    rustup.rs
                  </a>
                </p>
              </div>
            )}
          </CardContent>
        </Card>
      </div>

      {/* Generated Code */}
      <Card>
        <CardHeader className="pb-3">
          <div className="flex items-center justify-between">
            <CardTitle className="text-sm">run.py généré</CardTitle>
            <div className="flex gap-2">
              <Button size="sm" variant="outline" onClick={handleCopy}>
                <Copy className="h-4 w-4 mr-1" /> Copier
              </Button>
              <Button size="sm" variant="outline" onClick={handleDownload}>
                <Download className="h-4 w-4 mr-1" /> Télécharger
              </Button>
            </div>
          </div>
        </CardHeader>
        <CardContent>
          <pre className="bg-muted p-4 rounded-lg overflow-x-auto text-xs font-mono max-h-[400px] overflow-y-auto">
            {generatedCode}
          </pre>
        </CardContent>
      </Card>
    </div>
  );
}
